const students = [
  { id: "CS-1", name: "Emma", mark: 76 }, { id: "CS-2", name: "George", mark: 82 }, { id: "CS-3", name: "Mary", mark: 36 }, { id: "CS-4", name: "Jason", mark: 58 }, { id: "CS-5", name: "Karen", mark: 89 }, { id: "CS-6", name: "Carlos", mark: 86 }, { id: "CS-7", name: "Ko Ko", mark: 69 }, { id: "CS-8", name: "Kyaw Kyaw", mark: 52 }, { id: "CS-9", name: "Ma Ma", mark: 85 }, { id: "CS-10", name: "Su Su", mark: 57 }
];
const books = ["Software Engineering", "Networking", "Thomas Calculus", "JavaScript for Web Developers", "Linear Algebra", "Time Management", "HTML and CSS Basic", "Essay and Letter"];
const workspace = document.querySelector("#workspace");
function setWorkspace(content) { workspace.innerHTML = content; }
function updateClock() { document.querySelector("#current-time").textContent = new Intl.DateTimeFormat("en-GB", { dateStyle:"medium", timeStyle:"medium" }).format(new Date()); }
updateClock(); setInterval(updateClock, 1000);
function renderRollCall() { setWorkspace(`<div class="workspace-header"><h2>Second Year Roll Call</h2><button class="button button-green" id="save-roll" type="button">Save attendance</button></div><div class="table-wrap"><table><thead><tr><th>Roll no.</th><th>Name</th><th>Attendance</th></tr></thead><tbody>${students.slice(0,6).map(s => `<tr><td>${s.id}</td><td>${s.name}</td><td><select class="attendance-select" aria-label="Attendance for ${s.name}"><option>Present</option><option>Absent</option></select></td></tr>`).join("")}</tbody></table></div><p id="roll-message"></p>`); document.querySelector("#save-roll").onclick=()=>{const message=document.querySelector("#roll-message");message.className="message";message.textContent="Attendance has been recorded for this demonstration.";}; }
function renderBooks() { setWorkspace(`<div class="workspace-header"><h2>Library Books</h2></div><div class="form-row"><label>Choose a book<select id="book-choice">${books.map(book => `<option>${book}</option>`).join("")}</select></label><button class="button button-blue" id="borrow-book" type="button">Borrow selected book</button><button class="button button-green" id="random-book" type="button">Choose random book</button></div><p id="book-message"></p>`); const message=document.querySelector("#book-message");document.querySelector("#borrow-book").onclick=()=>{message.className="message";message.textContent=`“${document.querySelector("#book-choice").value}” is available to borrow.`;};document.querySelector("#random-book").onclick=()=>{message.className="message";message.textContent=`Try this book: “${books[Math.floor(Math.random()*books.length)]}”.`;}; }
function renderResults() { const highest=students.reduce((best,student)=>student.mark>best.mark?student:best); setWorkspace(`<div class="workspace-header"><h2>Exam Results</h2></div><div class="result-grid"><div class="result-card"><strong>Highest mark</strong><p>${highest.name} — ${highest.mark}</p></div>${students.map(s=>`<div class="result-card"><strong>${s.name}</strong><p>${s.id} · ${s.mark} marks</p></div>`).join("")}</div><hr><div class="form-row"><label>Demo password<input id="result-password" type="password"></label><label>Add marks to every student<input id="mark-increase" type="number" min="0" value="5"></label><button id="update-results" class="button button-amber" type="button">Update results</button></div><p id="result-message"></p>`);document.querySelector("#update-results").onclick=()=>{const message=document.querySelector("#result-message");if(document.querySelector("#result-password").value!=="kyawSann6789"){message.className="message error";message.textContent="Incorrect demo password.";return;}const increase=Number(document.querySelector("#mark-increase").value);if(!Number.isFinite(increase)||increase<0){message.className="message error";message.textContent="Enter a valid non-negative number.";return;}students.forEach(s=>s.mark+=increase);renderResults();}; }
function renderLogin() { setWorkspace(`<div class="workspace-header"><h2>Demo Login</h2></div><div class="form-row"><label>Email address<input id="email" type="email" placeholder="name@example.com" required></label><button id="login-button" class="button button-red" type="button">Log in</button></div><p id="login-message"></p>`);document.querySelector("#login-button").onclick=()=>{const email=document.querySelector("#email"),message=document.querySelector("#login-message"),valid=email.validity.valid&&email.value;message.className=valid?"message":"message error";message.textContent=valid?"Login successful (demonstration).":"Enter a valid email address.";}; }
function renderDockets() { setWorkspace(`<div class="workspace-header"><h2>Accounts</h2></div><div class="result-grid"><div class="result-card"><strong>Course fee</strong><p>Paid · Demo record</p></div><div class="result-card"><strong>Library fee</strong><p>Paid · Demo record</p></div><div class="result-card"><strong>Next payment</strong><p>Contact the school office.</p></div></div>`); }
document.querySelectorAll("[data-action]").forEach(button=>button.addEventListener("click",()=>({rollcall:renderRollCall,books:renderBooks,results:renderResults,login:renderLogin,dockets:renderDockets}[button.dataset.action])()));
